### ISSUE TITLE
ModuleNotFoundError: No module named 'ruamel.yaml'

### ISSUE THREAD

**Issue by adorton-adobe** [bajwa-adobe/ust-configapp#1]
I get the following error when I install the `pyapi` requirements and run app.py (I'm using a virtual environment):

`ModuleNotFoundError: No module named 'ruamel.yaml'`

I don't see `ruamel.yaml` in the requirements file.  If I install that package manually, I can run app.py.

**Comment by bajwa-adobe** [comment]
Please install python dependencies. The future version might not need it as python dependencies will be packaged as pex.
 
pip install -r requirements.txt
[requirements.txt](https://github.com/bajwa-adobe/ust-configapp/files/1784343/requirements.txt)

**Comment by adorton-adobe** [comment]
Right - what I'm saying is `ruamel.yaml` is not specified in `requirements.txt`.  I installed it, ran app.py, and got the error.  To prevent others from getting the same error, you need to add that library to the requirements file.

To reproduce the error:

1. Create a new Python virtual environment
2. Activate it
3. Install `requirements.txt`
4. Try to run `app.py`

**Comment by bajwa-adobe** [comment]
Thanks I have update the [requirements.txt](https://github.com/bajwa-adobe/ust-configapp/blob/master/pyapi/requirements.txt)
