### ISSUE TITLE
Convert the python module as PEX file

### ISSUE THREAD

**Issue by bajwa-adobe** [bajwa-adobe/ust-configapp#12]
We should convert python module to PEX and remove requirements to run requirements.txt

**Comment by adorton-adobe** [comment]
I suggest building the python component into a standalone executable that doesn't require a python interpreter to run.  I've been working with [pyinstaller](https://www.pyinstaller.org/) for the work I've been doing on the command-line config handler.

It uses a [spec file](https://github.com/adorton-adobe/ust-configapp/blob/feature/config-handler/config-handler/config-handler.spec) to tell what to build and how to build it.  If you want to build the config handler and test it, check out [this branch](https://github.com/adorton-adobe/ust-configapp/tree/feature/config-handler) of my fork and do the following:

```
$ pip install pyinstaller
$ cd /path/to/config-handler
$ pyinstaller config-handler.spec
```

If the build succeeds, you can find the executable in the `dist` directory.

```
$ ./dist/config-handler -h
```

pyinstaller can generate executables for Windows, Mac and Linux.

**Comment by adorton-adobe** [comment]
It also frees us from having to support Python 2.

**Comment by bajwa-adobe** [comment]
Pyinstaller sound a good option to remove python 2 compatibility issue. 

Closed - this is being worked on part of  [Implement ability to edit multiple Adobe side groups mappings](https://github.com/bajwa-adobe/ust-configapp/issues/11)
