### ISSUE TITLE
yarn start failure - "nf" not found

### ISSUE THREAD

**Issue by adorton-adobe** [bajwa-adobe/ust-configapp#4]
I get the following error when I run `yarn start`:

```
yarn run v1.5.1
$ nf start -p 3000
'nf' is not recognized as an internal or external command,
operable program or batch file.
```

It seems I need to install `node-forman`.  I recommend adding this dependency to package.json (if possible) or at least documenting it as a dependency.

**Comment by bajwa-adobe** [comment]
added `foreman` as `devDependencies`. It works now.
